development:
  adapter: postgresql
  encoding: unicode
  database: mstwjs_backbone_development
  pool: 5
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: mstwjs_backbone_test
  pool: 5
  host: localhost
